### ISSUE TITLE
--trace option doesn’t trace rule execution

### ISSUE THREAD

**Issue by Quintus** [jimweirich/rake#174]
`rake --trace` doesn’t print out the evaluation of rules. Take for example this Rakefile:

``` ruby
rule ".foo" => [".bar"] do |t|
  cp t.source, t.name
end

task :default => ["foo.foo"]
```

If `foo.bar` doesn’t exist, Rake will fail with `Don't know how to build task 'foo.foo'` (which I personally find confusing as it should be "Don't know how to build task 'foo.bar' as that is the missing file). Running rake with `--trace` gives this result:

```
** Invoke default (first_time)
rake aborted!
Don't know how to build task 'foo.foo'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task_manager.rb:49:in `[]'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:60:in `lookup_prerequisite'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:56:in `block in prerequisite_tasks'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:56:in `collect'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:56:in `prerequisite_tasks'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:185:in `invoke_prerequisites'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:165:in `block in invoke_with_call_chain'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:143:in `invoke_task'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `each'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:73:in `block in run'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
/opt/rubies/ruby-1.9.3-p385/lib/ruby/gems/1.9.1/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/opt/rubies/ruby-1.9.3-p385/bin/rake:23:in `load'
/opt/rubies/ruby-1.9.3-p385/bin/rake:23:in `<main>'
Tasks: TOP => default
```

Looking into the code of TaskManager#attempt_rule, there are multiple calls to TaskManager#trace_rule, but that method appearently never prints out anything, as can be seen from the output above.

Rake version is 10.0.3, Ruby version is `ruby 1.9.3p385 (2013-02-06 revision 39114) [x86_64-linux]`.

Vale,
Quintus

**Comment by jimweirich** [comment]
The rule you specified essentially says: If you are trying to build X.foo, and an X.bar exists, then this is how you build it.

Both conditions (trying to build X.foo AND X.bar exists) must be true for the rule to be considered.

This is important because there may be several ways to build X.foo and using X.bar is only one of the possibilities.

You are trying to build foo.foo.  foo.bar doesn't exist so the rule is never triggered.  Since the rule is never triggered, there is no output from the trace.

So, Rake is correct when it says it doesn't know how to build foo.foo.  It really doesn't know.

**Comment by Quintus** [comment]
OK, I see. Thanks for the explanation :-)
