### ISSUE TITLE
rake 0.9.6 test failures with jruby

### ISSUE THREAD

**Issue by graaff** [jimweirich/rake#201]
With jruby 1.6.8 (ruby-1.8.7-p357) (2013-06-03 fffffff) (OpenJDK 64-Bit Server VM 1.6.0_27) [linux-amd64-java] I'm seeing a number of test failures:

```
  1) Error:
TestRakeRules#test_create_with_source:
RuntimeError: Circular dependency detected: TOP => abc.c => abc.c
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/invocation_chain.rb:18:in `append'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/invocation_chain.rb:28:in `append'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:158:in `invoke_with_call_chain'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:187:in `invoke_prerequisites'
    org/jruby/RubyArray.java:1620:in `each'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:185:in `invoke_prerequisites'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:165:in `invoke_with_call_chain'
    /usr/share/jruby/lib/ruby/1.8/monitor.rb:191:in `mon_synchronize'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:159:in `invoke_with_call_chain'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:152:in `invoke'
    ./test/test_rake_rules.rb:50:in `test_create_with_source'
    org/jruby/RubyKernel.java:2105:in `send'

  2) Failure:
TestRakeRules#test_rule_runs_when_explicit_task_has_no_actions [./test/test_rake_rules.rb:166]:
Expected: ["abc.c"]
  Actual: []

  3) Error:
TestRakeRules#test_second_rule_runs_when_first_rule_doesnt:
RuntimeError: Circular dependency detected: TOP => abc.c => abc.c
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/invocation_chain.rb:18:in `append'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/invocation_chain.rb:28:in `append'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:158:in `invoke_with_call_chain'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:187:in `invoke_prerequisites'
    org/jruby/RubyArray.java:1620:in `each'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:185:in `invoke_prerequisites'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:165:in `invoke_with_call_chain'
    /usr/share/jruby/lib/ruby/1.8/monitor.rb:191:in `mon_synchronize'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:159:in `invoke_with_call_chain'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:152:in `invoke'
    ./test/test_rake_rules.rb:231:in `test_second_rule_runs_when_first_rule_doesnt'
    org/jruby/RubyKernel.java:2105:in `send'

  4) Error:
TestRakeRules#test_multiple_rules1:
RuntimeError: Don't know how to build task 'abc.c'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task_manager.rb:49:in `[]'
    /var/tmp/portage/dev-ruby/rake-0.9.6/work/all/rake-0.9.6/lib/rake/task.rb:321:in `[]'
    ./test/test_rake_rules.rb:27:in `test_multiple_rules1'
    org/jruby/RubyKernel.java:2105:in `send'

```

There are more test failures in this file, but they all seem to be related. Please let me know if you need the full set.

**Comment by jimweirich** [comment]
I just ran 0.9.6 against JRuby 1.7.3 and 1.6.8 and am seeing no errors.  Is it an envitonmental thing?

**Comment by graaff** [comment]
That's possible since I'm using the jruby version that comes with Gentoo. I actually encountered this issue trying to add rake 0.9.6 to Gentoo. I'll have a look in that direction, thanks for confirming that you don't see these issues.

**Comment by jimweirich** [comment]
I've added JRuby back into the CI mix and everything looks green (https://travis-ci.org/jimweirich/rake/builds/8265407).  I'm closing this issue.

**Comment by graaff** [comment]
Sounds good to me. It looks like we are having trouble with some of the unversioned jars in the jruby distribution, I suspect they are not as unversioned as they seem. In any case this looks like something to be fixed on our end. Thanks for the feedback!
