### ISSUE TITLE
Ruby 1.8.7 support

### ISSUE THREAD

**Issue by michelboaventura** [jimweirich/rake#226]
Hi,

Rake's website says that ruby 1.8.7 is supported, but some tests are written with some ruby 1.9 syntax. If I fix this syntax issues I got only two test errors, mainly because ruby 1.8.7 doesn't have `CONFIG['rubylibprefix']`:

``` Ruby
  1) Error:
TestBacktraceSuppression#test_near_system_dir_isnt_suppressed:
TypeError: can't convert nil into String
    ./test/test_rake_backtrace.rb:24:in `+'
    ./test/test_rake_backtrace.rb:24:in `test_near_system_dir_isnt_suppressed'

  2) Error:
TestBacktraceSuppression#test_system_dir_suppressed:
NoMethodError: undefined method `+' for nil:NilClass
    ./test/test_rake_backtrace.rb:15:in `test_system_dir_suppressed'
```

My question is: should I make a pull request fixing this issues or ruby 1.8.7 support will be dropped?

**Comment by michelboaventura** [comment]
Hum,

I just realized this is fixed on master. Sorry guys!
