### ISSUE TITLE
TestTask outputs stack trace on failed test run

### ISSUE THREAD

**Issue by decitrig** [jimweirich/rake#23]
Getting this output on a normal `rake test:unit` call. I haven't passed --trace to rake, nor have I set any options to output trace.

```
1 tests, 1 assertions, 1 failures, 0 errors, 0 skips

Test run options: --seed 21675
rake aborted!
Command failed with status (1): [/usr/bin/ruby -w -I"lib:." "/usr/lib/ruby/...]
/usr/lib/ruby/1.9.1/rake.rb:993:in `block in sh'
/usr/lib/ruby/1.9.1/rake.rb:1008:in `call'
/usr/lib/ruby/1.9.1/rake.rb:1008:in `sh'
/usr/lib/ruby/1.9.1/rake.rb:1092:in `sh'
/usr/lib/ruby/1.9.1/rake.rb:1027:in `ruby'
/usr/lib/ruby/1.9.1/rake.rb:1092:in `ruby'
/usr/lib/ruby/1.9.1/rake/testtask.rb:115:in `block (2 levels) in define'
/usr/lib/ruby/1.9.1/rake.rb:1110:in `verbose'
/usr/lib/ruby/1.9.1/rake/testtask.rb:100:in `block in define'
/usr/lib/ruby/1.9.1/rake.rb:634:in `call'
/usr/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
/usr/lib/ruby/1.9.1/rake.rb:629:in `each'
/usr/lib/ruby/1.9.1/rake.rb:629:in `execute'
/usr/lib/ruby/1.9.1/rake.rb:595:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/usr/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
/usr/lib/ruby/1.9.1/rake.rb:581:in `invoke'
/usr/lib/ruby/1.9.1/rake.rb:2041:in `invoke_task'
/usr/lib/ruby/1.9.1/rake.rb:2019:in `block (2 levels) in top_level'
/usr/lib/ruby/1.9.1/rake.rb:2019:in `each'
/usr/lib/ruby/1.9.1/rake.rb:2019:in `block in top_level'
/usr/lib/ruby/1.9.1/rake.rb:2058:in `standard_exception_handling'
/usr/lib/ruby/1.9.1/rake.rb:2013:in `top_level'
/usr/lib/ruby/1.9.1/rake.rb:1992:in `run'
/usr/bin/rake:31:in `<main>'
```

From Rakefile:

```
Rake::TestTask.new(:unit) do |t|
    t.test_files = TestFiles::UNIT
    t.libs << "."
    t.warning = true
end
```

**Comment by jimweirich** [comment]
can you also provide the test code that is causing the failure?

**Comment by decitrig** [comment]
```
require 'test/unit'

class ATest < Test::Unit::TestCase
    def test_sanity
        assert_equal(1, 2)
    end
 end
```

**Comment by decitrig** [comment]
whoops- didn't mean to close.

**Comment by jimweirich** [comment]
No problem, I reopened.

I'm not able to reproduce this.  What versions of rake & ruby are you using.  What platform are you on?  Anything unusual about your environment or setup?

**Comment by decitrig** [comment]
rake version 0.8.7
ruby version 1.9.2

I've seen this on OS X 10.5 and 64-bit archlinux. I don't _think_ there's anything unusual about my environment. Anything I should look for specifically?

**Comment by decitrig** [comment]
Confirmed also on fresh install of 64-bit ubuntu; same behavior, ruby 1.9.1, rake 0.8.7.

Is there more info I could provide?

**Comment by marcelokanzaki** [comment]
So, is there any fix for the verbose output? Its really annoying...

**Comment by thedaniel** [comment]
I'm seeing this as well.. what was the rationale for closing? fixed, wontfix, other?

**Comment by benatkin** [comment]
I'd like to see this fixed too. Please reopen first, and sort out why it was closed later.

**Comment by krainboltgreene** [comment]
I'm getting this same problem with the latest of everything:

```
Run options: --seed 56801

# Running:

..F

Finished in 0.001683s, 1782.5312 runs/s, 1782.5312 assertions/s.

  1) Failure:
TestExample#test_failure [/Users/krainboltgreene/Code/Ruby/gems/example_gem/test/lib/example_test.rb:5]:
Failed assertion, no message given.

3 runs, 3 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib" "/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/testtask.rb:104:in `block (3 levels) in define'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/file_utils.rb:82:in `ruby'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in `ruby'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/testtask.rb:100:in `block (2 levels) in define'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:58:in `verbose'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/testtask.rb:98:in `block in define'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/bin/ruby_noexec_wrapper:14:in `eval'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.3-p392@example_gem/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by krainboltgreene** [comment]
I've done some investigating and discovered a few things.

Here are my "suppressed paths":

``` ruby
Rake::Backtrace::SUPPRESSED_PATHS #=> ["/Users/krainboltgreene/.rvm/rubies/ruby-1.9.3-p392",
 "/Users/krainboltgreene/.rvm/rubies/ruby-1.9.3-p392/lib/ruby",
 "/Users/krainboltgreene/.rvm/rubies/ruby-1.9.3-p392/lib",
 "/Users/krainboltgreene/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1",
 "/Users/krainboltgreene/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1",
 "/Users/krainboltgreene/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/vendor_ruby/1.9.1",
 "/Users/krainboltgreene/Code/Ruby/gems/example_gem/gems/ruby/1/.9/.1/gems/rake/-10/.0/.4/lib"]
```

Here's the first line of my backtrace:

``` ruby
ex.backtrace.first #=> "/Users/krainboltgreene/Code/Ruby/gems/example_gem/Rakefile:22:in `block in <top (required)>'"
```

None of the suppressed paths cover even the FIRST line of the backtrace.
