### ISSUE TITLE
cannot load such file -- action_controller/metal/responder

### ISSUE THREAD

**Issue by dmshvetsov** [jimweirich/rake#289]
Rails '4.2.0.beta1'
Rake '10.3.2'

```
$ rake routes --trace
rake aborted!
LoadError: cannot load such file -- action_controller/metal/responder
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/inherited_resources-1.4.1/lib/inherited_resources/responder.rb:2:in `<module:InheritedResources>'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/inherited_resources-1.4.1/lib/inherited_resources/responder.rb:1:in `<top (required)>'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `block in require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/inherited_resources-1.4.1/lib/inherited_resources.rb:4:in `<top (required)>'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `block in require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/bundler/gems/activeadmin-36edd084f277/lib/active_admin.rb:10:in `<top (required)>'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/bundler/gems/activeadmin-36edd084f277/lib/activeadmin.rb:1:in `require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/bundler/gems/activeadmin-36edd084f277/lib/activeadmin.rb:1:in `<top (required)>'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/bundler-1.7.0/lib/bundler/runtime.rb:76:in `require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/bundler-1.7.0/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/bundler-1.7.0/lib/bundler/runtime.rb:72:in `each'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/bundler-1.7.0/lib/bundler/runtime.rb:72:in `block in require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/bundler-1.7.0/lib/bundler/runtime.rb:61:in `each'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/bundler-1.7.0/lib/bundler/runtime.rb:61:in `require'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/bundler-1.7.0/lib/bundler.rb:133:in `require'
/Users/Shvetsov/Sites/frcms_proto/config/application.rb:14:in `<top (required)>'
/Users/Shvetsov/Sites/frcms_proto/Rakefile:4:in `require'
/Users/Shvetsov/Sites/frcms_proto/Rakefile:4:in `<top (required)>'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in `load'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/lib/rake/application.rb:687:in `raw_load_rakefile'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/lib/rake/application.rb:93:in `load_rakefile'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/lib/rake/application.rb:77:in `block in run'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/bin/rake:23:in `load'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/bin/rake:23:in `<main>'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/bin/ruby_executable_hooks:15:in `eval'
/Users/Shvetsov/.rvm/gems/ruby-2.1.0@frcms_proto/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dmshvetsov** [comment]
installed gem inherited_resources (in my case 1.4.1 version) causing the problem

**Comment by drbrain** [comment]
I don't understand how this is a rake issue, can you clarify?

**Comment by dmshvetsov** [comment]
@drbrain you are absolutely right this is not rake issue, thanks.
https://github.com/josevalim/inherited_resources/issues/373
