### ISSUE TITLE
rake test broken in zsh

### ISSUE THREAD

**Issue by trobrock** [jimweirich/rake#53]
Since the upgrade from 0.8.4 to 0.9.2 my `rake test:units` and all related test commands has broken. I switched to bash and it works fine.

```
rake -t test:units
** Invoke test:units (first_time)
** Invoke db:test:prepare (first_time)
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations
** Execute db:test:prepare
** Invoke db:test:load (first_time)
** Invoke db:test:purge (first_time)
** Invoke environment 
** Execute db:test:purge
** Execute db:test:load
** Invoke db:schema:load (first_time)
** Invoke environment 
** Execute db:schema:load
** Execute test:units
/Users/trobrock/.rvm/rubies/ree-1.8.7-2010.02/bin/ruby -I"lib:test" -I"/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib" "/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/rake_test_loader.rb" "unit" 
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/rake_test_loader.rb:11:in `require': no such file to load -- /Users/trobrock/Sites/outright/unit (LoadError)
        from /Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/rake_test_loader.rb:11
        from /Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/rake_test_loader.rb:5:in `each'
        from /Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/rake_test_loader.rb:5
rake aborted!
Command failed with status (1): [/Users/trobrock/.rvm/rubies/ree-1.8.7-2010...]
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/file_utils.rb:53:in `create_shell_runner'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in `call'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in `sh'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/file_utils_ext.rb:36:in `sh'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/file_utils.rb:80:in `ruby'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/file_utils_ext.rb:36:in `ruby'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/testtask.rb:99:in `define'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/file_utils_ext.rb:57:in `verbose'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/testtask.rb:98:in `define'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/task.rb:205:in `execute'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/task.rb:158:in `invoke_with_call_chain'
/Users/trobrock/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/application.rb:62:in `run'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/gems/rake-0.9.2/bin/rake:32
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/bin/rake:19:in `load'
/Users/trobrock/.rvm/gems/ree-1.8.7-2010.02@outright-app/bin/rake:19
Tasks: TOP => test:units
```

**Comment by trobrock** [comment]
Seems like it works fine if I run `TEST=test/unit/**/*_test.rb rake test:units` something with the way FileList is loading the patterns I think.

Edit: Sorry I mean FileList is doing things properly, the other path seems to be the broken one:

https://github.com/jimweirich/rake/blob/master/lib/rake/testtask.rb#L133

```
        result = []
        result += @test_files.to_a if @test_files
        result << @pattern if @pattern
        result
```

**Comment by trobrock** [comment]
Seems to have randomly started working for me now
