### ISSUE TITLE
errors on 3 tests under MRI 1.8.7

### ISSUE THREAD

**Issue by terceiro** [jimweirich/rake#89]
Hi, currently there are three tests that crash under MRI 1.8.7. Note that everything passes under MRI 1.9.3:

```
$ git log -n 1
commit 47c6d8a506cd9cd900436a6ec5e62ea79fe83fec
Author: Jim Weirich <jim.weirich@gmail.com>
Date:   Sat Aug 6 01:32:28 2011 -0400

    Minor updates to the README for 0.9.3.
$ ruby -v
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
$ gem list

*** LOCAL GEMS ***

minitest (2.8.1)
$ ruby -Ilib bin/rake 
RDoc 2.4.2+ is required to build documentation
Run options: --seed 33123

# Running tests:

........................................................E..............E.................................................................................................................................................................................................................................................................................................................................................E..........................

Finished tests in 4.806590s, 90.7088 tests/s, 252.1538 assertions/s.

  1) Error:
test_classic_namespace(TestRakeApplicationOptions):
LoadError: no such file to load -- rake/classic_namespace
    /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    ./lib/rake/application.rb:293:in `standard_rake_options'
    /usr/lib/ruby/1.8/optparse.rb:1267:in `call'
    /usr/lib/ruby/1.8/optparse.rb:1267:in `parse_in_order'
    /usr/lib/ruby/1.8/optparse.rb:1254:in `catch'
    /usr/lib/ruby/1.8/optparse.rb:1254:in `parse_in_order'
    /usr/lib/ruby/1.8/optparse.rb:1248:in `order!'
    /usr/lib/ruby/1.8/optparse.rb:1339:in `permute!'
    /usr/lib/ruby/1.8/optparse.rb:1360:in `parse!'
    ./lib/rake/application.rb:428:in `handle_options'
    /tmp/rake/test/test_rake_application_options.rb:328:in `command_line'
    /tmp/rake/test/test_rake_application_options.rb:327:in `instance_eval'
    /tmp/rake/test/test_rake_application_options.rb:327:in `command_line'
    /tmp/rake/test/test_rake_application_options.rb:315:in `flags'
    /tmp/rake/test/test_rake_application_options.rb:315:in `catch'
    /tmp/rake/test/test_rake_application_options.rb:315:in `flags'
    /tmp/rake/test/test_rake_application_options.rb:312:in `each'
    /tmp/rake/test/test_rake_application_options.rb:312:in `flags'
    /tmp/rake/test/test_rake_application_options.rb:263:in `test_classic_namespace'

  2) Error:
test_clean(TestRakeClean):
LoadError: no such file to load -- rake/clean.rb
    /tmp/rake/test/test_rake_clean.rb:7:in `load'
    /tmp/rake/test/test_rake_clean.rb:7:in `test_clean'

  3) Error:
test_run_code_rake(TestRakeTestTask):
RuntimeError: unable to find rake lib
    ./lib/rake/testtask.rb:179:in `rake_lib_dir'
    ./lib/rake/testtask.rb:160:in `run_code'
    /tmp/rake/test/test_rake_test_task.rb:88:in `test_run_code_rake'

436 tests, 1212 assertions, 0 failures, 3 errors, 0 skips
rake aborted!
Command failed with status (1): [/usr/bin/ruby1.8 -w -I"lib:." -I"lib" "lib...]
./lib/rake/file_utils.rb:53:in `create_shell_runner'
./lib/rake/file_utils.rb:45:in `call'
./lib/rake/file_utils.rb:45:in `sh'
./lib/rake/file_utils_ext.rb:39:in `sh'
./lib/rake/file_utils.rb:82:in `ruby'
./lib/rake/file_utils_ext.rb:39:in `ruby'
./lib/rake/testtask.rb:99:in `define'
./lib/rake/file_utils_ext.rb:60:in `verbose'
./lib/rake/testtask.rb:98:in `define'
./lib/rake/task.rb:205:in `call'
./lib/rake/task.rb:205:in `execute'
./lib/rake/task.rb:200:in `each'
./lib/rake/task.rb:200:in `execute'
./lib/rake/task.rb:158:in `invoke_with_call_chain'
./lib/rake/task.rb:151:in `invoke_with_call_chain'
./lib/rake/task.rb:176:in `invoke_prerequisites'
./lib/rake/task.rb:174:in `each'
./lib/rake/task.rb:174:in `invoke_prerequisites'
./lib/rake/task.rb:157:in `invoke_with_call_chain'
./lib/rake/task.rb:151:in `invoke_with_call_chain'
./lib/rake/task.rb:144:in `invoke'
./lib/rake/application.rb:114:in `invoke_task'
./lib/rake/application.rb:93:in `top_level'
./lib/rake/application.rb:93:in `each'
./lib/rake/application.rb:93:in `top_level'
./lib/rake/application.rb:66:in `run'
./lib/rake/application.rb:131:in `standard_exception_handling'
./lib/rake/application.rb:63:in `run'
Tasks: TOP => default => test
(See full trace by running task with --trace)
$ rbenv global 1.9.3-debian 
$ ruby -v
ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]
$ gem list

*** LOCAL GEMS ***


$ ruby -Ilib bin/rake 
RDoc 2.4.2+ is required to build documentation
Run options: --seed 44389

# Running tests:

....................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished tests in 6.482400s, 67.2590 tests/s, 189.8988 assertions/s.

436 tests, 1231 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by jimweirich** [comment]
Getting a clean run on both 1.8.7 and 1.9.3 now:

<pre>
$ r18
Using /Users/jim/.rvm/gems/ruby-1.8.7-p352
$ rake
Run options: --seed 27222
# Running tests:
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................
Finished tests in 7.605361s, 58.1169 tests/s, 166.5930 assertions/s.
442 tests, 1267 assertions, 0 failures, 0 errors, 0 skips
$ penv
Using /Users/jim/.rvm/gems/ruby-1.9.3-p194
$ rake
Run options: --seed 11822
# Running tests:
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................
Finished tests in 9.583207s, 46.1223 tests/s, 132.2104 assertions/s.
442 tests, 1267 assertions, 0 failures, 0 errors, 0 skips
</pre>

**Comment by jimweirich** [comment]
The above is in Rake HEAD.

**Comment by derekatkins** [comment]
Ah, so 0.9.2.2 is still broken?  I just ran into this issue myself against 1.8.7-p370.

**Comment by jimweirich** [comment]
derekatkins - I'm more interested if either the 0.9.3 or 10.0.0 versions break.
